import os
import django
import random

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'booking_system.settings')
django.setup()

from bookings.models import Movie, Seat

movies_data = [
    {"title": "The Matrix", "genre": "Action, Sci-Fi", "rating": 8.7, "duration": 136, "poster": "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX300.jpg", "description": "A computer hacker learns from mysterious rebels about the true nature of his reality."},
    {"title": "Gladiator", "genre": "Action, Drama", "rating": 8.5, "duration": 155, "poster": "https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_SX300.jpg", "description": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family."},
    {"title": "The Godfather", "genre": "Crime, Drama", "rating": 9.2, "duration": 175, "poster": "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_SX300.jpg", "description": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son."},
    {"title": "Titanic", "genre": "Drama, Romance", "rating": 7.9, "duration": 195, "poster": "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX300.jpg", "description": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic."},
    {"title": "The Shawshank Redemption", "genre": "Drama", "rating": 9.3, "duration": 142, "poster": "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg", "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency."},
    {"title": "Pulp Fiction", "genre": "Crime, Drama", "rating": 8.9, "duration": 154, "poster": "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_SX300.jpg", "description": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine."},
    {"title": "Forrest Gump", "genre": "Drama, Romance", "rating": 8.8, "duration": 142, "poster": "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX300.jpg", "description": "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75."},
    {"title": "Interstellar", "genre": "Adventure, Drama, Sci-Fi", "rating": 8.6, "duration": 169, "poster": "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX300.jpg", "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."},
    {"title": "The Dark Knight", "genre": "Action, Crime, Drama", "rating": 9.0, "duration": 152, "poster": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg", "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."},
    {"title": "Inception", "genre": "Action, Sci-Fi", "rating": 8.8, "duration": 148, "poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg", "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O."},
    {"title": "Fight Club", "genre": "Drama", "rating": 8.8, "duration": 139, "poster": "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_SX300.jpg", "description": "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more."},
    {"title": "Goodfellas", "genre": "Biography, Crime, Drama", "rating": 8.7, "duration": 146, "poster": "https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_SX300.jpg", "description": "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito."},
    {"title": "The Silence of the Lambs", "genre": "Crime, Drama, Thriller", "rating": 8.6, "duration": 118, "poster": "https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_SX300.jpg", "description": "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims."},
    {"title": "Se7en", "genre": "Crime, Drama, Mystery", "rating": 8.6, "duration": 127, "poster": "https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjODdhMDU5NDM1XkEyXkFqcGc@._V1_SX300.jpg", "description": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives."},
    {"title": "City of God", "genre": "Crime, Drama", "rating": 8.6, "duration": 130, "poster": "https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_SX300.jpg", "description": "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin."},
    {"title": "The Lord of the Rings: The Return of the King", "genre": "Action, Adventure, Drama", "rating": 9.0, "duration": 201, "poster": "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_SX300.jpg", "description": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring."},
    {"title": "Spirited Away", "genre": "Animation, Adventure, Family", "rating": 8.6, "duration": 125, "poster": "https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_SX300.jpg", "description": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts."},
    {"title": "Saving Private Ryan", "genre": "Drama, War", "rating": 8.6, "duration": 169, "poster": "https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_SX300.jpg", "description": "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action."},
    {"title": "The Green Mile", "genre": "Crime, Drama, Fantasy", "rating": 8.6, "duration": 189, "poster": "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg", "description": "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift."},
    {"title": "Leon: The Professional", "genre": "Action, Crime, Drama", "rating": 8.5, "duration": 110, "poster": "https://m.media-amazon.com/images/M/MV5BNGRkYTNhOWQtYmI0Ni00MjZhLWJmMzAtMTA2Mjg4NGNiNDU0XkEyXkFqcGc@._V1_SX300.jpg", "description": "12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée."},
    {"title": "Terminator 2: Judgment Day", "genre": "Action, Sci-Fi", "rating": 8.5, "duration": 137, "poster": "https://m.media-amazon.com/images/M/MV5BNGMyMGNkMDUtMjc2Ni00NWFlLTgyODEtZTY2MzBiZTg0OWZiXkEyXkFqcGc@._V1_SX300.jpg", "description": "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from a more advanced and powerful cyborg."},
    {"title": "Back to the Future", "genre": "Adventure, Comedy, Sci-Fi", "rating": 8.5, "duration": 116, "poster": "https://m.media-amazon.com/images/M/MV5BZmM3ZjE0NzctNjBiOC00MDZmLTgzMTUtNGVlOWFlOTNiZDJiXkEyXkFqcGc@._V1_SX300.jpg", "description": "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend."},
    {"title": "Psycho", "genre": "Horror, Mystery, Thriller", "rating": 8.5, "duration": 109, "poster": "https://m.media-amazon.com/images/M/MV5BYjZhMzFiZjItODA3ZC00MmRhLWIzMGYtMmVjOWUwYTA3MTRjXkEyXkFqcGc@._V1_SX300.jpg", "description": "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother."},
    {"title": "The Pianist", "genre": "Biography, Drama, Music", "rating": 8.5, "duration": 150, "poster": "https://m.media-amazon.com/images/M/MV5BMjEwNmEwYjgtNTk3ZC00NjljLTg5ZDctZTY3ZGQwZjRkZmQxXkEyXkFqcGc@._V1_SX300.jpg", "description": "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II."},
    {"title": "Parasite", "genre": "Comedy, Drama, Thriller", "rating": 8.6, "duration": 132, "poster": "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_SX300.jpg", "description": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan."},
    {"title": "The Lion King", "genre": "Animation, Adventure, Drama", "rating": 8.5, "duration": 88, "poster": "https://m.media-amazon.com/images/M/MV5BZGRiZDZhZjItM2M3ZC00Y2IyLTk3Y2MtMWY5YjliNDFkZTJlXkEyXkFqcGc@._V1_SX300.jpg", "description": "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."},
    {"title": "Glengarry Glen Ross", "genre": "Crime, Drama, Mystery", "rating": 7.7, "duration": 100, "poster": "https://m.media-amazon.com/images/M/MV5BM2Q5NDA1ODctNmM4Yy00Yjk4LTg2ZTUtZTJjYzYyMjA2MTdmXkEyXkFqcGc@._V1_SX300.jpg", "description": "An examination of the machinations behind the scenes at a real estate office."},
    {"title": "Alien", "genre": "Horror, Sci-Fi", "rating": 8.4, "duration": 117, "poster": "https://m.media-amazon.com/images/M/MV5BN2NhMDk2MmEtZDQzOC00MmY5LThhYzAtMDdjZGFjOGZjMjdjXkEyXkFqcGc@._V1_SX300.jpg", "description": "After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form."},
    {"title": "Apocalypse Now", "genre": "Drama, Mystery, War", "rating": 8.4, "duration": 147, "poster": "https://m.media-amazon.com/images/M/MV5BZDhiMTljYjYtODc1Yy00MmEwLTg2OTYtYmE1YTRmNDE4MmEwXkEyXkFqcGc@._V1_SX300.jpg", "description": "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god."},
    {"title": "Memento", "genre": "Mystery, Thriller", "rating": 8.4, "duration": 113, "poster": "https://m.media-amazon.com/images/M/MV5BMGQ3Y2Q4NjktN2E4Ny00Y2Q2LTliZDUtZTNiNjRhY2I0NGIyXkEyXkFqcGc@._V1_SX300.jpg", "description": "A man with short-term memory loss attempts to track down his wife's murderer."},
    {"title": "The Departed", "genre": "Crime, Drama, Thriller", "rating": 8.5, "duration": 151, "poster": "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg", "description": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston."},
    {"title": "Whiplash", "genre": "Drama, Music", "rating": 8.5, "duration": 106, "poster": "https://m.media-amazon.com/images/M/MV5BMDFjOWFkYzktYzhhMC00NmYyLTkwY2EtYjViMDhmNzg0OGFkXkEyXkFqcGc@._V1_SX300.jpg", "description": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing."},
    {"title": "The Prestige", "genre": "Drama, Mystery, Sci-Fi", "rating": 8.5, "duration": 130, "poster": "https://m.media-amazon.com/images/M/MV5BMTM3MzQ5MjQ5OF5BMl5BanBnXkFtZTcwMTQ3NzMzMw@@._V1_SX300.jpg", "description": "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other."},
    {"title": "Grave of the Fireflies", "genre": "Animation, Drama, War", "rating": 8.5, "duration": 89, "poster": "https://m.media-amazon.com/images/M/MV5BNTY5MmE2OGMtN2IxNC00MDY4LTkwMGEtZDUzOTYyNWE0ZTNjXkEyXkFqcGc@._V1_SX300.jpg", "description": "A young boy and his little sister struggle to survive in Japan during World War II."},
    {"title": "Django Unchained", "genre": "Drama, Western", "rating": 8.4, "duration": 165, "poster": "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg", "description": "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner."},
    {"title": "The Shining", "genre": "Drama, Horror", "rating": 8.4, "duration": 146, "poster": "https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_SX300.jpg", "description": "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence."},
    {"title": "WALL·E", "genre": "Animation, Adventure, Family", "rating": 8.4, "duration": 98, "poster": "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg", "description": "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."},
    {"title": "American Beauty", "genre": "Drama", "rating": 8.3, "duration": 122, "poster": "https://m.media-amazon.com/images/M/MV5BMDI1MDE0OTMtMmI2MS00Yjc2LTg2MTItMWExYTg5NzA1OGUzXkEyXkFqcGc@._V1_SX300.jpg", "description": "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend."},
    {"title": "Avengers: Infinity War", "genre": "Action, Adventure, Sci-Fi", "rating": 8.4, "duration": 149, "poster": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg", "description": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos."},
    {"title": "Spider-Man: Into the Spider-Verse", "genre": "Animation, Action, Adventure", "rating": 8.4, "duration": 117, "poster": "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg", "description": "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat."},
    {"title": "Joker", "genre": "Crime, Drama, Thriller", "rating": 8.4, "duration": 122, "poster": "https://m.media-amazon.com/images/M/MV5BNzY3OWQ5NDktNWQ2OC00ZjdlLThkMmItMDhhNDk3NTFiZGU4XkEyXkFqcGc@._V1_SX300.jpg", "description": "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime."},
    {"title": "Oldboy", "genre": "Action, Drama, Mystery", "rating": 8.4, "duration": 120, "poster": "https://m.media-amazon.com/images/M/MV5BMTAwNzNjYWItZmI0Ni00ZTcyLWIwNWMtZjlmNGMxZTEyYTJmXkEyXkFqcGc@._V1_SX300.jpg", "description": "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days."},
    {"title": "Braveheart", "genre": "Biography, Drama, History", "rating": 8.3, "duration": 178, "poster": "https://m.media-amazon.com/images/M/MV5BNGMxZDBhNGQtYTZlNi00N2UzLWI4NDEtNmUzNWM2NTdmZDA0XkEyXkFqcGc@._V1_SX300.jpg", "description": "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England."},
    {"title": "Toy Story", "genre": "Animation, Adventure, Comedy", "rating": 8.3, "duration": 81, "poster": "https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_SX300.jpg", "description": "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room."},
    {"title": "Amélie", "genre": "Comedy, Romance", "rating": 8.3, "duration": 122, "poster": "https://m.media-amazon.com/images/M/MV5BOTNmYzY0MWQtZGZmNy00Y2Y4LWFmMDQtMTZjYTdiYzEwZGQ2XkEyXkFqcGc@._V1_SX300.jpg", "description": "Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love."},
    {"title": "Coco", "genre": "Animation, Adventure, Drama", "rating": 8.4, "duration": 105, "poster": "https://m.media-amazon.com/images/M/MV5BMDIyM2E2NTAtMzlhNy00ZGUxLWI1NjgtZDY5MzhiMDc5NGU3XkEyXkFqcGc@._V1_SX300.jpg", "description": "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather."},
    {"title": "The Truman Show", "genre": "Comedy, Drama", "rating": 8.1, "duration": 103, "poster": "https://m.media-amazon.com/images/M/MV5BNzA3ZjZlNzYtMTdjMy00NjMzLTk5ZGYtMTkyYzNiOGM1YmM3XkEyXkFqcGc@._V1_SX300.jpg", "description": "An insurance salesman discovers his whole life is actually a reality TV show."},
    {"title": "Mad Max: Fury Road", "genre": "Action, Adventure, Sci-Fi", "rating": 8.1, "duration": 120, "poster": "https://m.media-amazon.com/images/M/MV5BZDRkODJhOTgtOTc1OC00NTgzLTk4NjItNDgxZDY4YjlmNDY2XkEyXkFqcGc@._V1_SX300.jpg", "description": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners."},
    {"title": "Jurassic Park", "genre": "Action, Adventure, Sci-Fi", "rating": 8.1, "duration": 127, "poster": "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg", "description": "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose."},
    {"title": "Deadpool", "genre": "Action, Adventure, Comedy", "rating": 8.0, "duration": 108, "poster": "https://m.media-amazon.com/images/M/MV5BNzY3ZWU5NGQtOTViNC00ZWVmLTliNjAtNzViNzlkZWQ4YzQ4XkEyXkFqcGc@._V1_SX300.jpg", "description": "A fast-talking mercenary with a morbid sense of humor is subjected to a rogue experiment that leaves him with accelerated healing powers and a quest for revenge."},
    {"title": "Avatar", "genre": "Action, Adventure, Fantasy", "rating": 7.8, "duration": 162, "poster": "https://m.media-amazon.com/images/M/MV5BMDEzMmQwZjctZWU2My00MWNlLWE0NjItMDJlYTRlNGJiZjcyXkEyXkFqcGc@._V1_SX300.jpg", "description": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home."}
]

added_count = 0
for data in movies_data:
    movie, created = Movie.objects.get_or_create(
        title=data['title'],
        defaults=data
    )
    if created:
        added_count += 1
        print(f"Added movie: {movie.title}")
        
        # generate seats for the movie (100 seats, A1-A10, etc.)
        new_seats = []
        for row in ['A', 'B', 'C', 'D', 'E', 'F', 'G']:
            for num in range(1, 11):
                new_seats.append(Seat(
                    movie=movie,
                    seat_number=f"{row}{num}",
                    is_booked=random.choice([True, False, False, False])
                ))
        Seat.objects.bulk_create(new_seats)
    else:
        # Update poster if it was broken/changed
        if movie.poster != data['poster']:
            movie.poster = data['poster']
            movie.save(update_fields=['poster'])
            print(f"Fixed broken poster for: {movie.title}")

print(f"Total new movies added: {added_count}")
print("Movies seeded successfully")
