# Generated by Django 4.2.28 on 2026-03-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
    ]
