# Generated by Django 4.2.28 on 2026-03-31 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.movie'),
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('hall', models.CharField(choices=[('HALL_A', 'Hall A'), ('HALL_B', 'Hall B'), ('HALL_C', 'Hall C')], default='HALL_A', max_length=20)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=250.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='bookings.movie')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('movie', 'date', 'start_time', 'hall')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.screening'),
        ),
        migrations.AddField(
            model_name='seat',
            name='screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.screening'),
        ),
    ]
