# Generated by Django 4.2.28 on 2026-04-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, help_text='Release date from TMDB or manually set', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='TMDB movie ID (null for locally-added movies)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='', max_length=500),
        ),
    ]
