# Generated by Django 4.2.28 on 2026-03-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='Movie',
            new_name='movie',
        ),
    ]
