# Generated by Django 4.2.28 on 2026-03-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.CharField(default='', max_length=255),
        ),
    ]
